image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: outils.docapost.tech/gitlab/losaunier/configChecker
  img: elsaunier/configchecker
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - deploy

format:
  stage: test
  image: elsaunier/go-promtool-amtool:latest
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go get $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
  tags:
    - configChecker

compile:
  stage: build
  only:
    refs:
      - master
    changes:
      - .gitlab-ci.yml
      - Dockerfile
      - main.go
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/mybinary
  artifacts:
    paths:
      - mybinary
  tags:
    - configChecker

deploy:
  stage: deploy
  image: docker.docapost.tech/prod/docker-make:latest
  services:
  - docker:19.03.12-dind
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $img .
    - docker push $img
  after_script:
    - docker logout
  tags:
    - configChecker
