apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: configchecker-ingress
  
spec:
  rules:
    - host: configchecker.k8s.svc.docaposte.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: configchecker-svc
                port:
                  number: 30000

          - path: /verif
            pathType: Prefix
            backend:
              service:
                name: configchecker-svc
                port:
                  number: 30000