apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: configchecker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issue-temporary-certificate: 'true'
spec:
  tls:
  - hosts:
      - https-configchecker.k8s.svc.docaposte.cloud
    secretName: secret-tls   
  rules:
  - host: configchecker.k8s.svc.docaposte.cloud 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: configcheckerapp-svc
            port:
              number: 8181